# Generated by Django 4.2 on 2023-04-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_scissors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(choices=[('Камень', 'Камень'), ('Ножницы', 'Ножницы'), ('Бумага', 'Бумага')], max_length=10),
        ),
    ]
